INSERT INTO currencies (id, name, symbol, code, created_date, last_modified_date, version)
VALUES
    (100, 'United States Dollar', '$', 'USD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (101, 'Euro', '€', 'EUR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (102, 'British Pound', '£', 'GBP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (103, 'Japanese Yen', '¥', 'JPY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (104, 'Australian Dollar', 'A$', 'AUD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (105, 'Canadian Dollar', 'C$', 'CAD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (106, 'Swiss Franc', 'CHF', 'CHF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (107, 'Chinese Yuan', 'CN¥', 'CNY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (108, 'Swedish Krona', 'kr', 'SEK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (109, 'New Zealand Dollar', 'NZ$', 'NZD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (110, 'Hong Kong Dollar', 'HK$', 'HKD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (111, 'Singapore Dollar', 'S$', 'SGD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (112, 'Indian Rupee', '₹', 'INR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (113, 'South Korean Won', '₩', 'KRW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (114, 'Norwegian Krone', 'kr', 'NOK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (115, 'Danish Krone', 'kr', 'DKK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (116, 'Polish Zloty', 'zł', 'PLN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (117, 'Mexican Peso', '$', 'MXN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (118, 'Brazilian Real', 'R$', 'BRL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (119, 'South African Rand', 'R', 'ZAR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (120, 'Turkish Lira', '₺', 'TRY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (121, 'Czech Koruna', 'Kč', 'CZK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (122, 'Hungarian Forint', 'Ft', 'HUF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (123, 'Israeli New Shekel', '₪', 'ILS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (124, 'Saudi Riyal', '﷼', 'SAR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (125, 'United Arab Emirates Dirham', 'د.إ', 'AED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (126, 'Thai Baht', '฿', 'THB', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (127, 'Indonesian Rupiah', 'Rp', 'IDR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (128, 'Malaysian Ringgit', 'RM', 'MYR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
    (129, 'Philippine Peso', '₱', 'PHP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);